# Register user
POST http://localhost:1931/register
Content-Type: application/json

{
  "email": "pablo@example.com",
  "password": "123456",
  "username": "pagoru"
}

###

# Login user
POST http://localhost:1931/login
Content-Type: application/json

{
  "email": "pablo@example.com",
  "password": "123456"
}

###

# Verify session
POST http://localhost:1931/verify-session
Content-Type: application/json

{
  "sessionId": "r9rIuNUNmdGFdN263nlZinZxpjtACLts",
  "token": "fPEnGsTQFuoiTaHSDY541APf41D5EBs4Ewjfr9cLk9kf5IzACdKNwySwsAWKgKYA"
}

###

# Refresh session
POST http://localhost:1931/refresh-session
Content-Type: application/json

{
  "sessionId": "unOQaeWJWM4WMhPRdpIKfu6VtS86Rjab",
  "refreshToken": "AP6MLnY5pcFMSQOhMRTwIN6C4FFQMWy9p0TBEk0aIw8GrukHlxsDEY2fBKqy9xuqKYCdQc8f2f0sKRGbtBWjRg0L2KQnBxVMg0MekFxNJQOkyPXR0we3AkaJ76bEictT"
}

