# Create ticket
POST http://localhost:1931/create-ticket
Content-Type: application/json

{
  "redirectUrl": "example.com",
  "ticketKey": "THIS_IS_A_PRIVATE_TOKEN"
}

###

# Register user
POST http://localhost:1931/register
Content-Type: application/json

{
  "email": "pablo@example.com",
  "password": "123456",
  "username": "pagoru"
}

###

# Login user
POST http://localhost:1931/login
Content-Type: application/json

{
  "ticketId": "8b2f1929-4cf4-4989-b10e-14f2fb7b8a78",
  "email": "pablo@example.com",
  "password": "123456"
}

###

# Claim session
POST http://localhost:1931/claim-session
Content-Type: application/json

{
  "ticketId": "98ae6e67-f2aa-4733-8b40-4f12e76516b7",
  "ticketKey": "THIS_IS_A_PRIVATE_TOKEN",

  "sessionId": "57343474-3cdf-42af-a86d-276f7ff06a01",
  "token": "lYRzusLunSAkHppWr7vpuR2LcPrnHk4uDhTXGbYeGu22LEigXZpQNdQ8cp3TbEfA"
}

###

# Refresh session
POST http://localhost:1931/refresh-session
Content-Type: application/json

{
  "ticketId": "98ae6e67-f2aa-4733-8b40-4f12e76516b7",
  "sessionId": "57343474-3cdf-42af-a86d-276f7ff06a01",
  "refreshToken": "TvpaXlNfA2NAjplCtfVd5hELFp62V47gdZ2IuiJhQ8BV3U79pLILDgukubGLQBmeEkKwMbD9OWkte4gPtT3K0q2glN7hGTbaOLS3xxqveBLg156GbkLRCw1XugiYzMFD"
}

